array_width = 80
attr_fn_like_width = 80
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "PreferSameLine"
chain_width = 80
combine_control_expr = true
comment_width = 50
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
edition = "2018"
empty_item_single_line = true
enum_discrim_align_threshold = 12
error_on_line_overflow = true
error_on_unformatted = true
fn_call_width = 80
fn_params_layout = "Tall"
fn_single_line = false
force_multiline_blocks = false
format_code_in_doc_comments = true
format_generated_files = false
format_macro_matchers = true
format_strings = true
group_imports = "StdExternalCrate"
hard_tabs = false
hide_parse_errors = false
ignore = ['src/utils/emotes.rs']
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 120
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
preserve_block_start_blank_lines = false
preserve_closure_block_wrapping = false
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
single_line_if_else_max_width = 60
space_after_colon = true
space_before_colon = false
space_before_fn_sig_paren = false
spaces_around_ranges = false
space_around_attr_eq = true
struct_field_align_threshold = 12
struct_lit_single_line = false
struct_lit_width = 0
struct_variant_width = 0
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = false
wrap_comments = true
