name: Add latest tag to new release
on:
  release:
    types: [published]

jobs:
  run:
    name: Add/update tag to new release
    runs-on: ubuntu-latest

    steps:
    - name: Run latest-tag
      uses: EndBug/latest-tag@latest
